### ISSUE TITLE
Minor typo in slides

### ISSUE THREAD

**Issue by smigniot** [HoLyVieR/prototype-pollution-nsec18#1]
Replace - Did some fuzzing with this file to identity which content could help us inject arbitrary code.
By - Did some fuzzing with this file to _identify_ which content could help us inject arbitrary code.

And thanks for these slides !

**Comment by HoLyVieR** [comment]
Fixed in [1c0f890b](https://github.com/HoLyVieR/prototype-pollution-nsec18/commit/1c0f890b8b8fa79bdf0e1eb2fd7f7d3aa89df2de).
